version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "shinypythonstackname"
s3_bucket = "shiny-wt-test-bucket1"
s3_prefix = "shinypythonstackname"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
image_repositories = []
